import {test,expect} from '@playwright/test';
test('paste transform inputs invalidate old candidates and pass reviewed units to apply',async({page})=>{
  await page.goto('/tests/fixtures/clipboard.html?ready');
  await page.getByRole('button',{name:'Preview CAD paste',exact:true}).click();
  await page.getByLabel('Clipboard paste scale').fill('0');
  await expect(page.getByLabel('CAD paste candidate')).toHaveCount(0);
  await page.getByRole('button',{name:'Preview CAD paste',exact:true}).click();
  await expect(page.locator('.clipboard-panel > p[role="status"]')).toContainText('positive and finite');
  await page.getByLabel('Clipboard paste scale').fill('1.5');
  await page.getByLabel('Clipboard paste rotation').fill('-30');
  await page.getByRole('button',{name:'Preview CAD paste',exact:true}).click();
  await expect(page.locator('#result')).toContainText('Rotation -30, scale 1.5.');
  await page.getByRole('button',{name:'Apply reviewed CAD paste',exact:true}).click();
  await expect(page.locator('#result')).toContainText('rotation -30, scale 1.5');
});
test('JWS requires explicit positive units and retains compatibility warnings before paste',async({page})=>{
  await page.goto('/tests/fixtures/clipboard.html?ready');
  await page.getByRole('button',{name:'Browse JWS part',exact:true}).focus();await page.keyboard.press('Enter');
  await expect(page.getByLabel('JWS part file')).toHaveValue('/parts/door.jws');
  await expect(page.getByRole('button',{name:'Load checked JWS part',exact:true})).toBeDisabled();
  await page.getByLabel('JWS coordinate scale').fill('-1');
  await page.getByRole('button',{name:'Load checked JWS part',exact:true}).click();
  await expect(page.locator('.clipboard-panel > p[role="status"]')).toContainText('finite and positive');
  await expect(page.getByLabel('CAD clipboard contents')).toContainText('House');
  await page.getByLabel('JWS coordinate scale').fill('100');
  await page.getByRole('button',{name:'Load checked JWS part',exact:true}).focus();await page.keyboard.press('Enter');
  await expect(page.getByLabel('CAD clipboard contents')).toContainText('JWS symbol');
  await expect(page.getByLabel('JWS part import')).toContainText('Exact round-trip: false');
  await expect(page.getByLabel('JWS compatibility report JSON')).toHaveValue(/binary-source/);
  await expect(page.getByLabel('JWS part import')).toContainText('Palette and fonts are replacements');
  await page.getByRole('button',{name:'Preview CAD paste',exact:true}).click();
  await expect(page.getByLabel('CAD paste candidate')).toBeVisible();
  await page.setViewportSize({width:375,height:812});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.goto('/tests/fixtures/clipboard.html?ready&jwsloaded');
  await expect(page.getByLabel('JWS compatibility report JSON')).toHaveValue(/binary-source/);
});
test('unsupported JWS retains a full report and the previous clipboard',async({page})=>{
  await page.goto('/tests/fixtures/clipboard.html?ready&jwsblocked');
  await page.getByLabel('JWS part file').fill('/parts/unknown.jws');
  await page.getByLabel('JWS coordinate scale').fill('1');
  await page.getByRole('button',{name:'Load checked JWS part',exact:true}).click();
  await expect(page.getByLabel('JWS part import')).toContainText('Unsupported record class');
  await expect(page.getByLabel('CAD clipboard contents')).toContainText('House');
  await expect(page.locator('.clipboard-panel > p[role="status"]')).toContainText('existing clipboard was preserved');
});
test('copy preserves source and reviewed paste uses coordinates and keyboard activation',async({page})=>{
  await page.goto('/tests/fixtures/clipboard.html');
  await page.getByLabel('Clipboard base point').fill('10,20');
  await page.getByRole('button',{name:'Copy selected to CAD clipboard',exact:true}).click();
  await expect(page.locator('#result')).toContainText('Copied from 10,20 (include_references); source preserved.');
  await expect(page.getByLabel('CAD clipboard contents')).toContainText('2 entities');
  await page.getByLabel('Clipboard paste point').fill('20000,30000');
  await page.getByRole('button',{name:'Preview CAD paste',exact:true}).click();
  await expect(page.getByLabel('CAD paste candidate')).toContainText('Pasted entities: 2');
  await expect(page.locator('#result')).toHaveText('Preview at 20000,30000; source preserved.');
  expect(await page.evaluate(()=>Reflect.get(window,'compromised'))).toBeUndefined();
  await page.getByRole('button',{name:'Apply reviewed CAD paste',exact:true}).focus();await page.keyboard.press('Enter');
  await expect(page.locator('#result')).toHaveText('Applied paste-reviewed at 20000,30000');
  await expect(page.getByLabel('CAD paste candidate')).toHaveCount(0);
});
test('invalid placement and source errors discard the candidate and retain the clipboard',async({page})=>{
  await page.goto('/tests/fixtures/clipboard.html?ready&stale');
  await page.getByRole('button',{name:'Preview CAD paste',exact:true}).click();
  await page.getByLabel('Clipboard paste point').fill('nan,0');
  await expect(page.getByLabel('CAD paste candidate')).toHaveCount(0);
  await page.getByRole('button',{name:'Preview CAD paste',exact:true}).click();
  await expect(page.locator('.clipboard-panel > p[role="status"]')).toContainText('finite x,y');
  await page.getByLabel('Clipboard paste point').fill('0,0');
  await page.getByRole('button',{name:'Preview CAD paste',exact:true}).click();
  await page.getByRole('button',{name:'Apply reviewed CAD paste',exact:true}).click();
  await expect(page.locator('.clipboard-panel > p[role="status"]')).toContainText('Source changed');
  await expect(page.getByLabel('CAD paste candidate')).toHaveCount(0);
  await expect(page.getByLabel('CAD clipboard contents')).toBeVisible();
});
test('checker errors block paste and mappings fit mobile width',async({page})=>{
  await page.goto('/tests/fixtures/clipboard.html?ready&blocked');
  await page.getByRole('button',{name:'Preview CAD paste',exact:true}).click();
  await expect(page.getByRole('button',{name:'Apply reviewed CAD paste',exact:true})).toBeDisabled();
  await expect(page.getByLabel('CAD paste candidate')).toContainText('Dimension target is missing.');
  await page.locator('.clipboard-mappings summary').click();
  await expect(page.locator('.clipboard-mappings')).toContainText('new_door');
  await page.setViewportSize({width:375,height:812});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('button',{name:'Discard paste preview',exact:true}).click();
  await expect(page.getByLabel('CAD paste candidate')).toHaveCount(0);
});
test('portable parts load and save without overwriting existing files',async({page})=>{
  await page.goto('/tests/fixtures/clipboard.html');
  await page.getByRole('button',{name:'Browse CAD part',exact:true}).focus();await page.keyboard.press('Enter');
  await expect(page.getByLabel('CAD part file')).toHaveValue('/parts/door.cadpart.json');
  await page.getByRole('button',{name:'Load CAD part',exact:true}).focus();await page.keyboard.press('Enter');
  await expect(page.getByLabel('CAD clipboard contents')).toContainText('House');
  await page.getByRole('button',{name:'Save new CAD part',exact:true}).focus();await page.keyboard.press('Enter');
  await expect(page.locator('#result')).toHaveText('Saved new part /parts/door.cadpart.json');
  await page.getByRole('button',{name:'Save new CAD part',exact:true}).click();
  await expect(page.locator('.clipboard-panel > p[role="status"]')).toContainText('Output already exists');
});
test('read-only drawings can provide parts and empty selection cannot copy',async({page})=>{
  await page.goto('/tests/fixtures/clipboard.html?readonly');
  await page.getByRole('button',{name:'Copy selected to CAD clipboard',exact:true}).click();
  await expect(page.getByRole('button',{name:'Preview CAD paste',exact:true})).toBeDisabled();
  await expect(page.getByRole('button',{name:'Save new CAD part',exact:true})).toBeEnabled();
  await page.goto('/tests/fixtures/clipboard.html?empty');
  await expect(page.getByRole('button',{name:'Copy selected to CAD clipboard',exact:true})).toBeDisabled();
});
