import {test,expect} from '@playwright/test';
test('part folder displays checked thumbnails, warnings and paged keyboard selection',async({page})=>{
  await page.goto('/tests/fixtures/part-library.html');
  await page.getByRole('button',{name:'Browse part folder',exact:true}).focus();await page.keyboard.press('Enter');
  await expect(page.getByLabel('Part library folder')).toHaveValue('/parts');
  await page.getByRole('button',{name:'Load part folder',exact:true}).focus();await page.keyboard.press('Enter');
  await expect(page.locator('.part-library-card')).toHaveCount(12);
  expect(await page.evaluate(()=>Reflect.get(window,'compromised'))).toBeUndefined();
  await expect(page.locator('.part-library-thumbnail image')).toHaveCount(0);
  await expect(page.getByRole('button',{name:'Use part door.jws',exact:true})).toBeDisabled();
  await expect(page.getByRole('button',{name:'Use part bad.jws',exact:true})).toBeDisabled();
  await page.getByText('JWS compatibility report',{exact:true}).focus();await page.keyboard.press('Enter');await page.keyboard.press('Tab');
  await expect(page.getByLabel('JWS report for bad.jws')).toBeFocused();
  await expect(page.getByLabel('JWS report for bad.jws')).toHaveValue(/Unknown record class/);
  await page.getByLabel('Part library JWS scale').fill('100');
  await expect(page.getByLabel('Part library results')).toHaveCount(0);
  await page.getByRole('button',{name:'Load part folder',exact:true}).click();
  await page.getByRole('button',{name:'Use part door.jws',exact:true}).focus();await page.keyboard.press('Enter');
  await expect(page.locator('#result')).toHaveText('Loaded /parts/door.jws');
  await expect(page.locator('#result')).toHaveAttribute('data-jws','true');
  await page.getByRole('button',{name:'Next part page',exact:true}).click();
  await expect(page.locator('.part-library-card')).toHaveCount(2);
  await page.getByRole('button',{name:'Use part 12-wall.cadpart.json',exact:true}).click();
  await expect(page.locator('#result')).toHaveText('Loaded /parts/12-wall.cadpart.json');
  await page.setViewportSize({width:375,height:812});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('button',{name:'Previous part page',exact:true}).click();
  await expect(page.locator('.part-library-card')).toHaveCount(12);
});
test('stale library bytes preserve the clipboard and invalid scale discards old pages',async({page})=>{
  await page.goto('/tests/fixtures/part-library.html?ready&stale');
  await page.getByRole('button',{name:'Use part 00-wall.cadpart.json',exact:true}).click();
  await expect(page.locator('.part-library-panel > p[role="status"]')).toContainText('changed since');
  await expect(page.locator('#result')).toHaveText('Clipboard preserved.');
  await page.getByLabel('Part library JWS scale').fill('0');
  await expect(page.getByLabel('Part library results')).toHaveCount(0);
  await page.getByRole('button',{name:'Load part folder',exact:true}).click();
  await expect(page.locator('.part-library-panel > p[role="status"]')).toContainText('finite and positive');
});
