import {expect,test} from "@playwright/test";
test("scaled sheet views preview before applying, preserve local clips, and invalidate changed conditions",async({page})=>{
  await page.goto("/tests/fixtures/sheet.html");
  const apply=page.getByRole("button",{name:"Apply reviewed sheet views"});
  await expect(apply).toBeDisabled();
  await page.getByRole("button",{name:"Add sheet view"}).click();
  await page.getByRole("textbox",{name:"View 1 name",exact:true}).fill("Plan");
  await page.getByRole("textbox",{name:"View 1 model origin",exact:true}).fill("1000,2000");
  await page.getByRole("button",{name:"Add sheet view"}).click();
  await page.getByRole("textbox",{name:"View 2 name",exact:true}).fill("Detail");
  await page.getByRole("combobox",{name:"View 2 drawing",exact:true}).selectOption("detail");
  await page.getByRole("textbox",{name:"View 2 paper position",exact:true}).fill("150,10");
  await page.getByRole("textbox",{name:"View 2 scale",exact:true}).fill("1/20");
  await page.getByRole("listbox",{name:"View 2 layers",exact:true}).selectOption(["walls"]);
  await page.getByRole("button",{name:"Preview scaled sheet"}).click();
  await expect(page.locator("output")).toHaveText("No changes.");await expect(apply).toBeEnabled();
  await page.getByText("Sheet calculation and source report",{exact:true}).focus();
  await page.keyboard.press("Enter");await page.keyboard.press("Tab");
  await expect(page.getByRole("textbox",{name:"Scaled sheet report JSON",exact:true})).toBeFocused();
  await page.keyboard.press("Enter");await expect(page.locator("output")).toHaveText("No changes.");
  await expect(page.locator(".sheet-preview-svg image, .sheet-preview-svg script")).toHaveCount(0);
  expect(await page.evaluate(()=>Reflect.get(window,"sheetHacked"))).toBeUndefined();
  const clip=await page.locator(".sheet-preview-svg clipPath").getAttribute("id");
  await expect(page.locator(".sheet-preview-svg g")).toHaveAttribute("clip-path",`url(#${clip})`);
  await page.getByRole("textbox",{name:"View 2 paper size",exact:true}).fill("80,100");await expect(apply).toBeDisabled();
  await page.getByRole("button",{name:"Preview scaled sheet"}).click();await apply.click();
  expect(JSON.parse(await page.locator("output").innerText())).toEqual({hash:"reviewed-source",views:[{name:"Plan",drawing:"plan",origin:[1000,2000],at_mm:[10,10],size_mm:[100,100],scale:"1/100",layers:[]},{name:"Detail",drawing:"detail",origin:[0,0],at_mm:[150,10],size_mm:[80,100],scale:"1/20",layers:["walls"]}]});
  await page.getByRole("button",{name:"Remove view 2"}).click();await page.getByRole("button",{name:"Remove view 1"}).click();
  await page.getByRole("button",{name:"Preview scaled sheet"}).focus();await page.keyboard.press("Enter");await expect(apply).toBeEnabled();
  await page.keyboard.press("Tab");await page.getByRole("button",{name:"Apply reviewed sheet views"}).click();
  expect(JSON.parse(await page.locator("output").innerText()).views).toEqual([]);
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test("invalid viewport coordinates and stale sources never remain applicable",async({page})=>{
  await page.goto("/tests/fixtures/sheet.html?stale");
  await page.getByRole("button",{name:"Add sheet view"}).click();
  await page.getByRole("textbox",{name:"View 1 paper size",exact:true}).fill("0,100");
  await page.getByRole("button",{name:"Preview scaled sheet"}).click();
  await expect(page.locator("p[role=status]")).toContainText("positive");
  await expect(page.getByRole("button",{name:"Apply reviewed sheet views"})).toBeDisabled();
  await page.getByRole("textbox",{name:"View 1 paper size",exact:true}).fill("100,100");
  await page.getByRole("button",{name:"Preview scaled sheet"}).click();
  await page.getByRole("button",{name:"Apply reviewed sheet views"}).click();
  await expect(page.locator("p[role=status]")).toContainText("source changed");
  await expect(page.getByRole("button",{name:"Apply reviewed sheet views"})).toBeDisabled();
  await expect(page.locator("output")).toHaveText("No changes.");
});
